# '''
# second step:
# train the coarse model for 1.5 epochs with a batch size of 32, with 4 images per subject
# with ğœ†ğ‘â„ğ‘œ=2.0, ğœ†ğ‘–ğ‘‘=0.2, ğœ†ğ‘ ğ‘=1.0, ğœ†ğ‘™ğ‘šğ‘˜=1.0, ğœ†ğ‘’ğ‘¦ğ‘’=1.0, ğœ†ğœ·=1ğ‘’âˆ’4, and ğœ†ğ=1ğ‘’âˆ’4.

# Time:
# around 15min/1000iterations
# in total, needs around
output_dir: "/home/wang/wal/demo_test/DECA/train/step_2_coarse"
pretrained_modelpath: "/home/wang/wal/demo_test/DECA/data/deca_model.tar"
dataset:
  batch_size: 8
  K: 1
train:
  resume: True
  max_epochs: 20
  max_steps: 200000
  log_steps: 50
  vis_steps: 500
  checkpoint_steps: 1000
  val_steps: 500
  eval_steps: 1000
  lr: 5e-4
model:
  E_flame_backbone: 'convnext_v2_atto'
  face_eye_mask_path: "/home/wang/wal/demo_test/DECA/data/uv_face_eye_mask_y.png"
  #resnet50 convnext_v1  convnext_v2_tiny convnext_v2_atto

# loss:
#   shape_consistency: False
#   detail_consistency: False
#   useSeg: False
# python main_train.py --cfg configs/release_version/deca_coarse.yml